name: remote ssh command
on: 
  push:
    branches:
      - "main"
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 34.76.77.3
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd ~/icklink
          git pull
          docker-compose up -d --build